package com.lms.shared;

import jakarta.persistence.*;
import lombok.Getter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Abstract JPA superclass shared by every entity in the application.
 *
 * <p>Provides:
 * <ul>
 *   <li>UUID primary key — generated by the JPA provider (Hibernate 6 {@link GenerationType#UUID}).</li>
 *   <li>{@code created_at} — populated automatically by Spring Data JPA auditing.</li>
 * </ul>
 *
 * <p>Entities that also need an {@code updated_at} column should declare it directly
 * with {@link org.springframework.data.annotation.LastModifiedDate}.
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
@Getter
public abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
}
