package com.lms.seed;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.lms.modules.timetable.TimetableService;
import com.lms.modules.transcript.TranscriptService;
import com.lms.seed.SeedCatalog.CourseDef;
import com.lms.seed.SeedCatalog.CourseKind;
import com.lms.seed.SeedCatalog.GradeBand;
import com.lms.seed.SeedCatalog.GradingScaleDef;
import com.lms.seed.SeedCatalog.PloDef;
import com.lms.seed.SeedCatalog.ProgramDef;
import com.lms.seed.SeedModel.ClassMeeting;
import com.lms.seed.SeedModel.Course;
import com.lms.seed.SeedModel.Offering;
import com.lms.seed.SeedModel.Person;
import com.lms.seed.SeedModel.Student;
import com.lms.seed.SeedModel.Term;
import com.lms.shared.events.EnrollmentEvent;
import com.lms.shared.events.SemesterEvent;
import jakarta.persistence.EntityManager;
import lombok.extern.slf4j.Slf4j;
import org.springframework.cache.Cache;
import org.springframework.cache.CacheManager;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import java.math.BigDecimal;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Fills the database with four and a half years of demo data (Spring 2022 –
 * Fall 2026) for the BS CS, BS SE, BS AI and MS CS programs.
 *
 * <p>Everything runs in one transaction, so a failed run leaves the database
 * as it was. Rows are written with plain JDBC rather than through the module
 * services: the services publish a Kafka event per write, which would send
 * thousands of notifications, and they cannot back-date {@code created_at}.
 * Transcripts are the exception — they are generated by
 * {@link TranscriptService} itself, so GPAs and CLO/PLO attainment are
 * exactly what the app computes. The current term's weekly timetable is built
 * the same way, by {@link TimetableService}, over the seeded rooms.
 *
 * <p>Nothing here runs on a normal application start; see {@link SeedCommand}.
 */
@Slf4j
@Component
class DatabaseSeeder {

    static final String ADMIN_EMAIL = "admin@lms.local";
    static final String PASSWORD = "password";
    static final int STUDENTS_PER_BATCH = 30;
    static final String STAFF_DOMAIN = "lms.edu.pk";
    static final String STUDENT_DOMAIN = "student.lms.edu.pk";

    private static final long RANDOM_SEED = 20220829L;

    private final JdbcTemplate jdbc;
    private final PlatformTransactionManager transactionManager;
    private final PasswordEncoder passwordEncoder;
    private final TranscriptService transcriptService;
    private final TimetableService timetableService;
    private final ObjectMapper objectMapper;
    private final CacheManager cacheManager;
    private final EntityManager entityManager;

    DatabaseSeeder(JdbcTemplate jdbc, PlatformTransactionManager transactionManager,
                   PasswordEncoder passwordEncoder, TranscriptService transcriptService,
                   TimetableService timetableService, ObjectMapper objectMapper, CacheManager cacheManager, EntityManager entityManager) {
        this.jdbc = jdbc;
        this.transactionManager = transactionManager;
        this.passwordEncoder = passwordEncoder;
        this.transcriptService = transcriptService;
        this.timetableService = timetableService;
        this.objectMapper = objectMapper;
        this.cacheManager = cacheManager;
        this.entityManager = entityManager;
    }

    /** Thrown when seeding would clash with data already in the database. */
    static class SeedRefusedException extends RuntimeException {
        SeedRefusedException(String message) {
            super(message);
        }
    }

    record Result(Map<String, Long> counts, LocalDate asOf, Map<String, String> sampleLogins) {}

    /**
     * @param clean remove every row from every application table first
     * @param today activity in the current (open) term is generated up to this
     *              day, clamped into that term
     */
    Result seed(boolean clean, LocalDate today) {
        Result result = new TransactionTemplate(transactionManager).execute(status -> {
            if (clean) {
                truncateAll();
            } else {
                requireNoDemoData();
            }
            return new Run(today).execute();
        });
        clearCaches();
        return result;
    }

    private void truncateAll() {
        List<String> tables = jdbc.queryForList("""
                SELECT table_name FROM information_schema.tables
                WHERE  table_schema = current_schema()
                AND    table_type = 'BASE TABLE'
                AND    table_name <> 'flyway_schema_history'
                """, String.class);
        if (!tables.isEmpty()) {
            jdbc.execute("TRUNCATE TABLE "
                    + tables.stream().map(t -> '"' + t + '"').collect(Collectors.joining(", "))
                    + " RESTART IDENTITY CASCADE");
        }
        log.info("Removed all rows from {} tables", tables.size());
    }

    private void requireNoDemoData() {
        String programCodes = SeedCatalog.PROGRAMS.stream()
                .map(p -> "'" + p.code() + "'").collect(Collectors.joining(", "));
        long clashes = count("SELECT COUNT(*) FROM programs WHERE code IN (" + programCodes + ")")
                + count("SELECT COUNT(*) FROM courses WHERE code IN ("
                        + SeedCatalog.courses().keySet().stream().map(c -> "'" + c + "'")
                                .collect(Collectors.joining(", ")) + ")")
                + count("SELECT COUNT(*) FROM users WHERE email LIKE '%@" + STAFF_DOMAIN + "'"
                        + " OR email LIKE '%@" + STUDENT_DOMAIN + "'");
        if (clashes > 0) {
            throw new SeedRefusedException("The database already contains demo programs, courses or users. "
                    + "Run the seed command with --clean to delete all data and seed again.");
        }
    }

    private long count(String sql) {
        Long n = jdbc.queryForObject(sql, Long.class);
        return n == null ? 0 : n;
    }

    private void clearCaches() {
        try {
            for (String name : cacheManager.getCacheNames()) {
                Cache cache = cacheManager.getCache(name);
                if (cache != null) cache.clear();
            }
        } catch (RuntimeException e) {
            log.warn("Seeded, but could not clear the caches ({}). Flush Redis or restart the app "
                    + "before using it.", e.getMessage());
        }
    }

    // ── One seeding run ──────────────────────────────────────────────────────

    private record Batch(ProgramDef program, int intakeYear, List<Student> students) {}

    private final class Run {

        private final Random rnd = new Random(RANDOM_SEED);
        private final SeedTables t = new SeedTables(new SeedWriter(jdbc), objectMapper);
        private final ActivityGenerator activity = new ActivityGenerator(t, rnd);
        private final List<Term> terms = Term.all();
        private final Term openTerm = terms.get(terms.size() - 1);
        private final LocalDate asOf;
        private final String passwordHash = passwordEncoder.encode(PASSWORD);
        private final Set<String> emails = new HashSet<>();

        private UUID adminId;
        private final Map<String, UUID> programIds = new HashMap<>();
        private final Map<String, List<UUID>> ploIds = new HashMap<>();
        private final Map<String, Course> courses = new LinkedHashMap<>();
        private final Map<String, List<Person>> teachersByDepartment = new LinkedHashMap<>();
        private final Map<String, Person> courseTeacher = new HashMap<>();
        private final List<Person> assistants = new ArrayList<>();
        private final List<Batch> batches = new ArrayList<>();
        private final Map<String, UUID> semesterIds = new HashMap<>();
        private final Map<Person, Integer> openTermLoad = new HashMap<>();
        private int assistantCursor;

        Run(LocalDate today) {
            LocalDate earliest = openTerm.start().plusDays(28);
            LocalDate latest = openTerm.end().minusDays(1);
            this.asOf = today.isBefore(earliest) ? earliest : today.isAfter(latest) ? latest : today;
        }

        Result execute() {
            admin();
            programs();
            gradingScales();
            staff();
            courses();
            students();
            semesters();
            rooms();
            t.flush();

            for (Term term : terms) {
                if (term == openTerm) {
                    openTerm();
                } else {
                    for (ProgramDef program : SeedCatalog.PROGRAMS) {
                        for (Offering offering : offerings(program, term)) {
                            activity.generate(offering);
                        }
                        t.flush();
                        closeSemester(program, term);
                    }
                }
                log.info("Seeded {}", term.name());
            }
            t.flush();

            Map<String, Long> counts = new LinkedHashMap<>(t.counts());
            counts.put("transcripts", count("SELECT COUNT(*) FROM transcripts"));
            counts.put("rooms", count("SELECT COUNT(*) FROM rooms"));
            counts.put("timetable_entries", count("SELECT COUNT(*) FROM timetable_entries"));
            return new Result(counts, asOf, sampleLogins());
        }

        // ── Reference data ───────────────────────────────────────────────────

        private void admin() {
            List<UUID> existing = jdbc.queryForList("SELECT id FROM users WHERE email = ?", UUID.class, ADMIN_EMAIL);
            emails.add(ADMIN_EMAIL);
            if (!existing.isEmpty()) {
                adminId = existing.get(0);
                return;
            }
            adminId = UUID.randomUUID();
            t.users.add(adminId, "System Admin", ADMIN_EMAIL, passwordHash, "ADMIN", "ACTIVE",
                    LocalDateTime.of(2022, 1, 1, 9, 0));
        }

        private void programs() {
            LocalDateTime created = LocalDateTime.of(2022, 1, 2, 10, 0);
            for (ProgramDef p : SeedCatalog.PROGRAMS) {
                UUID id = UUID.randomUUID();
                programIds.put(p.code(), id);
                t.programs.add(id, p.name(), p.code(), p.description(), p.durationYears(), "ACTIVE", created);
                List<UUID> plos = new ArrayList<>();
                for (int i = 0; i < p.plos().size(); i++) {
                    PloDef plo = p.plos().get(i);
                    UUID ploId = UUID.randomUUID();
                    plos.add(ploId);
                    t.plos.add(ploId, id, "PLO-" + (i + 1), plo.title(), plo.description(), i + 1, created);
                }
                ploIds.put(p.code(), plos);
            }
        }

        private void gradingScales() {
            boolean globalDefaultExists = count(
                    "SELECT COUNT(*) FROM grading_scales WHERE program_id IS NULL AND is_default") > 0;
            LocalDateTime created = LocalDateTime.of(2022, 1, 2, 11, 0);
            for (GradingScaleDef scale : SeedCatalog.GRADING_SCALES) {
                UUID id = UUID.randomUUID();
                UUID programId = scale.programCode() == null ? null : programIds.get(scale.programCode());
                boolean isDefault = programId != null || !globalDefaultExists;
                t.gradingScales.add(id, programId, scale.name(), isDefault, created);
                for (int i = 0; i < scale.bands().size(); i++) {
                    GradeBand b = scale.bands().get(i);
                    t.gradingScaleEntries.add(UUID.randomUUID(), id, b.letter(), BigDecimal.valueOf(b.min()),
                            BigDecimal.valueOf(b.max()), BigDecimal.valueOf(b.points()), i + 1, created);
                }
            }
        }

        private void staff() {
            LocalDateTime created = LocalDateTime.of(2022, 1, 3, 9, 0);
            LocalDate joined = LocalDate.of(2022, 1, 3);
            int employeeNo = 1001;
            for (var entry : SeedCatalog.TEACHERS_PER_DEPARTMENT.entrySet()) {
                String dept = entry.getKey();
                List<Person> teachers = new ArrayList<>();
                for (int i = 0; i < entry.getValue(); i++) {
                    String designation = SeedCatalog.DESIGNATIONS.get(i % SeedCatalog.DESIGNATIONS.size());
                    String[] name = personName();
                    String display = (designation.contains("Professor") ? "Dr. " : "") + name[0] + " " + name[1];
                    Person p = new Person(UUID.randomUUID(), display, email(name[0] + "." + name[1], STAFF_DOMAIN));
                    teachers.add(p);
                    t.users.add(p.id(), p.name(), p.email(), passwordHash, "TEACHER", "ACTIVE", created);
                    t.teacherProfiles.add(p.id(), "EMP-" + employeeNo++, dept, designation, phone(), joined,
                            designation + ", Department of " + dept + ". Research interests: "
                            + INTERESTS.get(dept).get(i % INTERESTS.get(dept).size()) + ".", created);
                }
                teachersByDepartment.put(dept, teachers);
            }

            List<String> taDepartments = List.of(SeedCatalog.DEPT_CS, SeedCatalog.DEPT_SE, SeedCatalog.DEPT_AI);
            for (int i = 0; i < SeedCatalog.ASSISTANT_COUNT; i++) {
                String[] name = personName();
                Person p = new Person(UUID.randomUUID(), name[0] + " " + name[1],
                        email(name[0] + "." + name[1], STAFF_DOMAIN));
                assistants.add(p);
                String dept = taDepartments.get(i % taDepartments.size());
                t.users.add(p.id(), p.name(), p.email(), passwordHash, "ASSISTANT", "ACTIVE", created);
                t.teacherProfiles.add(p.id(), "TA-" + (2001 + i), dept, "Teaching Assistant", phone(),
                        joined, "Teaching assistant, Department of " + dept + ".", created);
            }

            // One teacher per course, round-robin within its department, so the
            // same person teaches a course every time it is offered.
            Map<String, Integer> next = new HashMap<>();
            for (String code : curriculumCourseCodes()) {
                String dept = SeedCatalog.course(code).department();
                List<Person> pool = teachersByDepartment.get(dept);
                int n = next.merge(dept, 1, Integer::sum) - 1;
                courseTeacher.put(code, pool.get(n % pool.size()));
            }
        }

        private void courses() {
            LocalDateTime created = LocalDateTime.of(2022, 1, 2, 12, 0);
            for (CourseDef def : SeedCatalog.courses().values()) {
                UUID id = UUID.randomUUID();
                t.courses.add(id, def.code(), def.name(), def.description(), def.creditHours(), "ACTIVE", created);
                List<UUID> cloIds = new ArrayList<>();
                for (int i = 0; i < def.clos().size(); i++) {
                    UUID cloId = UUID.randomUUID();
                    cloIds.add(cloId);
                    String clo = def.clos().get(i);
                    t.clos.add(cloId, id, "CLO-" + (i + 1), clo, cloDescription(clo, def.kind()), i + 1, created);
                }
                courses.put(def.code(), new Course(id, def, cloIds));
            }

            for (ProgramDef p : SeedCatalog.PROGRAMS) {
                List<UUID> plos = ploIds.get(p.code());
                Set<String> codes = new LinkedHashSet<>();
                p.semesters().forEach(codes::addAll);
                for (String code : codes) {
                    Course c = courses.get(code);
                    for (int i = 0; i < c.cloCount(); i++) {
                        t.cloPloMappings.add(c.cloIds().get(i), plos.get(ploIndex(p, c.def(), i)), null, created);
                    }
                }
            }
        }

        private void students() {
            for (int year = Term.FIRST_YEAR; year <= Term.LAST_YEAR; year++) {
                LocalDateTime created = LocalDate.of(year, 1, 3).atTime(10, 0);
                for (ProgramDef p : SeedCatalog.PROGRAMS) {
                    UUID cohortId = UUID.randomUUID();
                    t.cohorts.add(cohortId, p.code() + " Batch " + year,
                            p.name() + " — Spring " + year + " intake (cohort " + p.cohortNo() + ")", created);
                    List<Student> students = new ArrayList<>();
                    for (int serial = 1; serial <= STUDENTS_PER_BATCH; serial++) {
                        String roll = SeedCatalog.rollNumber(year, p.cohortNo(), serial);
                        String[] name = personName();
                        String email = roll + "@" + STUDENT_DOMAIN;
                        emails.add(email);
                        double ability = Math.max(0.40, Math.min(0.99, 0.77 + 0.10 * rnd.nextGaussian()));
                        Student s = new Student(UUID.randomUUID(), name[0] + " " + name[1], email, roll, ability);
                        students.add(s);
                        t.users.add(s.id(), s.name(), s.email(), passwordHash, "STUDENT", "ACTIVE", created);
                        t.studentProfiles.add(s.id(), roll, phone(), address(), LocalDate.of(year, 1, 8), created);
                        t.cohortMembers.add(cohortId, s.id(), created);
                    }
                    batches.add(new Batch(p, year, students));
                }
            }
        }

        private void semesters() {
            for (ProgramDef p : SeedCatalog.PROGRAMS) {
                for (Term term : terms) {
                    UUID id = UUID.randomUUID();
                    semesterIds.put(p.code() + "/" + term.index(), id);
                    boolean open = term == openTerm;
                    t.semesters.add(id, programIds.get(p.code()), term.name(), term.start(), term.end(),
                            open ? "OPEN" : "CLOSED", open ? null : term.closedAt(), open ? null : adminId,
                            term.start().minusDays(5).atTime(9, 0));
                }
            }
        }

        /**
         * The campus: 12 lecture rooms and 8 labs across the academic block and
         * each department's block. Sized for a batch of 30 with room to spare,
         * so the generator always has a room that fits and picks the snuggest.
         */
        private void rooms() {
            String sql = "INSERT INTO rooms (id, name, building, capacity, kind, created_at) VALUES (?, ?, ?, ?, ?, ?)";
            LocalDateTime created = terms.get(0).start().minusDays(30).atTime(9, 0);
            // prefix, building, lecture rooms, labs
            Object[][] blocks = {
                    {"A", "Academic Block", 6, 0},
                    {"CS", "Computer Science Block", 2, 4},
                    {"SE", "Software Engineering Block", 2, 2},
                    {"AI", "AI Block", 2, 2},
            };
            int[] capacities = {40, 50, 60};
            int lab = 1;
            for (Object[] block : blocks) {
                for (int i = 1; i <= (int) block[2]; i++) {
                    jdbc.update(sql, UUID.randomUUID(), block[0] + "-" + (100 + i), block[1],
                            capacities[(i - 1) % capacities.length], "LECTURE", created);
                }
                for (int i = 1; i <= (int) block[3]; i++) {
                    jdbc.update(sql, UUID.randomUUID(), "Computing Lab " + lab++, block[1], 40, "LAB", created);
                }
            }
        }

        /**
         * The current term. Every program's offerings are created first so the
         * timetable is generated over all of them at once, as the admin's
         * Generate button does. Course activity is then written against that
         * timetable, so attendance is taken on the days, at the times and in
         * the rooms the timetable shows.
         */
        private void openTerm() {
            List<Offering> offerings = new ArrayList<>();
            for (ProgramDef program : SeedCatalog.PROGRAMS) {
                offerings.addAll(offerings(program, openTerm));
            }
            t.flush();
            timetableService.generate();

            Map<UUID, List<ClassMeeting>> schedule = new HashMap<>();
            jdbc.query("""
                    SELECT e.psc_id, e.day_of_week, e.start_time, e.end_time, r.name, e.kind
                    FROM   timetable_entries e
                    JOIN   rooms r ON r.id = e.room_id
                    ORDER  BY e.day_of_week, e.start_time
                    """, rs -> {
                schedule.computeIfAbsent(rs.getObject(1, UUID.class), k -> new ArrayList<>())
                        .add(new ClassMeeting(DayOfWeek.of(rs.getInt(2)), rs.getObject(3, LocalTime.class),
                                rs.getObject(4, LocalTime.class), rs.getString(5), "LAB".equals(rs.getString(6))));
            });
            for (Offering offering : offerings) {
                activity.generate(offering.withSchedule(schedule.getOrDefault(offering.id(), List.of())));
            }
            t.flush();
        }

        // ── Terms ────────────────────────────────────────────────────────────

        /** Offers every active batch's semester courses and enrolls the batch's cohort in each. */
        private List<Offering> offerings(ProgramDef program, Term term) {
            boolean open = term == openTerm;
            LocalDate cutoff = open ? asOf : term.end().plusDays(1);
            UUID semesterId = semesterIds.get(program.code() + "/" + term.index());
            LocalDateTime created = term.start().minusDays(5).atTime(10, 0);
            LocalDateTime enrolledAt = term.start().minusDays(3).atTime(10, 0);
            List<Offering> offerings = new ArrayList<>();
            int shift = 0;

            for (Batch batch : batches) {
                if (batch.program() != program) continue;
                int semester = term.semesterNumberOf(batch.intakeYear());
                if (semester < 1 || semester > program.semesters().size()) continue;

                for (String code : program.semesters().get(semester - 1)) {
                    Course course = courses.get(code);
                    Person teacher = courseTeacher.get(code);
                    Person assistant = assistants.get(assistantCursor++ % assistants.size());
                    UUID pscId = UUID.randomUUID();
                    t.offerings.add(pscId, semesterId, course.id(), teacher.id(), program.maxCapacity(), created);
                    t.courseAssistants.add(pscId, assistant.id(), created);
                    if (open) openTermLoad.merge(teacher, 1, Integer::sum);

                    List<Student> active = new ArrayList<>();
                    for (Student s : batch.students()) {
                        LocalDateTime droppedAt = rnd.nextDouble() < 0.01
                                ? term.start().plusDays(14 + rnd.nextInt(21)).atTime(12, 0) : null;
                        if (droppedAt != null && !droppedAt.toLocalDate().isBefore(cutoff)) droppedAt = null;
                        String status = droppedAt != null ? "DROPPED" : open ? "ACTIVE" : "COMPLETED";
                        t.enrollments.add(UUID.randomUUID(), pscId, s.id(), status, droppedAt, enrolledAt,
                                "STUDENT", enrolledAt);
                        enrollmentEvent(EnrollmentEvent.Action.ENROLLED, s, pscId, course, program, term, enrolledAt);
                        if (droppedAt != null) {
                            enrollmentEvent(EnrollmentEvent.Action.DROPPED, s, pscId, course, program, term, droppedAt);
                        } else {
                            active.add(s);
                        }
                    }
                    offerings.add(new Offering(pscId, term, open, cutoff, program.name(), course, teacher,
                            assistant, active, shift++ % 5, List.of()));
                }
            }
            return offerings;
        }

        private void closeSemester(ProgramDef program, Term term) {
            UUID semesterId = semesterIds.get(program.code() + "/" + term.index());
            UUID programId = programIds.get(program.code());
            transcriptService.generateTranscriptsForSemesterNow(semesterId, programId, ADMIN_EMAIL);
            // Transcripts are saved through JPA; the next semester's CGPA is read with JDBC
            entityManager.flush();
            entityManager.clear();

            LocalDateTime closedAt = term.closedAt();
            jdbc.update("UPDATE transcripts SET generated_at = ?, created_at = ? WHERE semester_id = ?",
                    closedAt, closedAt, semesterId);

            SemesterEvent event = SemesterEvent.builder()
                    .occurredAt(instant(closedAt)).action(SemesterEvent.Action.CLOSED)
                    .semesterId(semesterId).semesterName(term.name())
                    .programId(programId).programName(program.name())
                    .triggeredByEmail(ADMIN_EMAIL).build();
            t.publishedEvent(SeedTables.SEMESTER_TRANSCRIPT_LISTENER, event, closedAt);
            t.publishedEvent(SeedTables.SEMESTER_NOTIFICATION_LISTENER, event, closedAt);
        }

        private void enrollmentEvent(EnrollmentEvent.Action action, Student s, UUID pscId, Course course,
                                     ProgramDef program, Term term, LocalDateTime when) {
            t.publishedEvent(SeedTables.ENROLLMENT_LISTENER, EnrollmentEvent.builder()
                    .occurredAt(instant(when)).action(action)
                    .studentId(s.id()).studentEmail(s.email()).studentName(s.name())
                    .programSemesterCourseId(pscId).courseCode(course.def().code())
                    .courseName(course.def().name()).semesterName(term.name()).programName(program.name())
                    .build(), when);
        }

        /** Accounts worth demoing: the busiest teacher this term and the batch topper. */
        private Map<String, String> sampleLogins() {
            Map<String, String> logins = new LinkedHashMap<>();
            logins.put("Admin", ADMIN_EMAIL);
            Person teacher = openTermLoad.entrySet().stream()
                    .max(Map.Entry.<Person, Integer>comparingByValue()
                            .thenComparing(e -> e.getKey().email(), Comparator.reverseOrder()))
                    .map(Map.Entry::getKey).orElseThrow();
            logins.put("Teacher (" + teacher.name() + ")", teacher.email());
            logins.put("Assistant (" + assistants.get(0).name() + ")", assistants.get(0).email());
            batches.stream()
                    .filter(b -> b.program().code().equals("BSCS") && b.intakeYear() == 2024)
                    .flatMap(b -> b.students().stream())
                    .max(Comparator.comparingDouble(Student::ability))
                    .ifPresent(s -> logins.put("Student (" + s.name() + ", BSCS 2024)", s.email()));
            return logins;
        }

        // ── Helpers ──────────────────────────────────────────────────────────

        private Set<String> curriculumCourseCodes() {
            Set<String> codes = new LinkedHashSet<>();
            SeedCatalog.PROGRAMS.forEach(p -> p.semesters().forEach(codes::addAll));
            return codes;
        }

        private String[] personName() {
            List<String> firstNames = rnd.nextDouble() < 0.45
                    ? SeedCatalog.FEMALE_FIRST_NAMES : SeedCatalog.MALE_FIRST_NAMES;
            return new String[]{
                    firstNames.get(rnd.nextInt(firstNames.size())),
                    SeedCatalog.SURNAMES.get(rnd.nextInt(SeedCatalog.SURNAMES.size()))};
        }

        private String email(String localPart, String domain) {
            String base = localPart.toLowerCase(Locale.ENGLISH).replaceAll("[^a-z.]", "");
            String email = base + "@" + domain;
            for (int n = 2; !emails.add(email); n++) {
                email = base + n + "@" + domain;
            }
            return email;
        }

        private String phone() {
            return String.format("03%02d-%07d", rnd.nextInt(50), rnd.nextInt(10_000_000));
        }

        private String address() {
            return "House " + (1 + rnd.nextInt(250)) + ", Street " + (1 + rnd.nextInt(30)) + ", "
                    + SeedCatalog.AREAS.get(rnd.nextInt(SeedCatalog.AREAS.size())) + ", "
                    + SeedCatalog.CITIES.get(rnd.nextInt(SeedCatalog.CITIES.size()));
        }
    }

    // ── OBE mappings ─────────────────────────────────────────────────────────

    /**
     * Which PLO (0-based) a course's CLO supports. BS: computing CLOs build up
     * PLO-2 to PLO-5, humanities CLOs PLO-7 to PLO-9, and project CLOs cover
     * analysis, teamwork, design and communication. MS: knowledge, analysis
     * and research.
     */
    static int ploIndex(ProgramDef program, CourseDef course, int cloIndex) {
        boolean project = course.kind() == CourseKind.PROJECT;
        if (program.code().equals("MSCS")) {
            int[] map = project ? new int[]{1, 2, 1, 3} : new int[]{0, 2, 1, 0};
            return map[cloIndex % map.length];
        }
        if (project) return new int[]{2, 5, 3, 6}[cloIndex % 4];
        if (course.code().startsWith("HU")) return new int[]{6, 7, 8}[cloIndex % 3];
        return new int[]{1, 2, 3, 4}[cloIndex % 4];
    }

    private static final Map<String, String> BLOOM_LEVELS = bloomLevels();

    private static Map<String, String> bloomLevels() {
        Map<String, String> m = new HashMap<>();
        for (String v : List.of("Explain", "Describe", "Discuss", "Comprehend", "Summarise"))
            m.put(v, "C2 (Understand)");
        for (String v : List.of("Apply", "Use", "Solve", "Compute", "Write", "Implement", "Configure", "Convert",
                "Represent", "Communicate", "Plan", "Prepare", "Carry", "Perform", "Manipulate", "Process",
                "Specify", "Estimate", "Measure", "Refactor", "Model", "Deploy", "Test", "Identify"))
            m.put(v, "C3 (Apply)");
        for (String v : List.of("Analyse", "Compare", "Classify", "Formulate", "Conduct"))
            m.put(v, "C4 (Analyse)");
        for (String v : List.of("Evaluate", "Critique", "Validate", "Prove", "Verify", "Defend"))
            m.put(v, "C5 (Evaluate)");
        for (String v : List.of("Design", "Develop", "Construct", "Build", "Create", "Pitch", "Present",
                "Demonstrate", "Revise"))
            m.put(v, "C6 (Create)");
        return m;
    }

    private static String cloDescription(String clo, CourseKind kind) {
        String verb = clo.split(" ", 2)[0];
        String level = BLOOM_LEVELS.getOrDefault(verb, "C3 (Apply)");
        return "Cognitive domain, Bloom's taxonomy level " + level + ". Assessed through "
                + (kind == CourseKind.PROJECT ? "reports and evaluations by the panel."
                                              : "quizzes, assignments and exams.");
    }

    private static final Map<String, List<String>> INTERESTS = Map.of(
            SeedCatalog.DEPT_CS, List.of("distributed systems and cloud computing", "computer networks",
                    "algorithms and complexity", "database systems", "information security",
                    "compilers and programming languages", "computer graphics", "parallel computing"),
            SeedCatalog.DEPT_SE, List.of("requirements engineering", "software architecture",
                    "software testing and quality", "agile methods", "empirical software engineering"),
            SeedCatalog.DEPT_AI, List.of("machine learning", "computer vision", "natural language processing",
                    "reinforcement learning", "robotics"),
            SeedCatalog.DEPT_HS, List.of("applied mathematics", "statistics", "English linguistics",
                    "Pakistan studies", "physics", "Islamic studies"));

    private static java.time.Instant instant(LocalDateTime when) {
        return when.atZone(ZoneId.systemDefault()).toInstant();
    }
}
